import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/Components/navbar";
import Footer from "@/Components/footer";
;





export const metadata: Metadata = {
  title: "Kano Process Trading Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100"
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
